dbconf:
  driver: mysql # 数据库类型 mysql, sqlite3, postgres, sqlserver
  hostname: 127.0.0.1  #服务器地址 本地建议 127.0.0.1
  hostport: 3309  #端口 默认3306
  username: root #用户名
  password: aa123456 #密码
  database: gofly_open #数据库名
  prefix: #数据表前缀
  sqlmode: "NO_ENGINE_SUBSTITUTION" #设置数据库sql_mode，当数据库类型mariadb/mysql可设置，不设置留空

log:
  level: info  # 日志等级debug
  root_dir: ./runtime/logs # 日志根目录
  filename: app.log # 日志文件名称
  format: json # 写入格式 可选json
  show_line: true # 是否显示调用行
  max_backups: 3 # 旧文件的最大个数
  max_size: 500 # 日志文件最大大小（MB）
  max_age: 28 # 旧文件的最大保留天数
  compress: true # 是否压缩

app:
  version: 1.3.2 #版本号
  env: dev #环境状态：dev=开发，pro=生产
  port: 8108 #运行服务端口（根据您的实际情况修改）
  apisecret: giles@888 #接口合法性验证
  #接口JWT验证、跨域域名-不添加请求时报403 (开发、部署必改),部署域名时：“https://en.goflys.cn”替换成您的域名
  allowurl: http://localhost:9105,http://localhost:9106,https://en.goflys.cn,http://localhost:6020
  tokenouttime: 10 #token超时时间单位分钟
  cpunum: 3 #调用cpu个数
  runlogtype: debug # Gin 框架在运行的时候默认是debug模式 有： 开发：debug，生产：release，测试模式：test
  vueobjroot: # 配置代码生成时-前端代码根目录位置(开发必改)
  companyPrivateHouse: #配置企业私有仓网址
  rootview: webbusiness # 配置根域名访问重定向路径,默认是业务端后台
  noVerifyTokenRoot: resource,webbusiness,webadmin,wxapp #不需要token-根模块
  noVerifyAPIRoot: resource,webbusiness,webadmin #不需要api接口合法性验证-根模块md5加密
  #不需要验证token-具体请求路径
  noVerifyToken: /common/uploadfile/get_image,/common/install/index,/common/install/save,/admin/user/login,/admin/user/logout,/admin/user/refreshtoken,/admin/user/get_code,/admin/user/resetPassword,/business/user/login,/business/user/logout,/business/user/refreshtoken,/business/user/get_code,/business/user/resetPassword,/wxoffi/service/getPost_api,/wxapp/user/get_openid,/admin/user/get_logininfo,/business/user/get_logininfo
  #不需要接口合法性-具体请求路径
  noVerifyAPI: /wxoffi/service/getPost_api,/common/install/index,/common/install/save,